### ISSUE TITLE
Day 28 Lab - Get rid of corpse code & extra view controller

### ISSUE THREAD

**Issue by elaewin** [thegrimheep/Objective-C_Intro#11]
You have a bit of commented out code in your project that needs to be cleaned up.

Also, you have an extraneous view controller on your storyboard that should be deleted.

**Comment by thegrimheep** [comment]
deleted the extra view controller and cleaned up the code.

**Comment by elaewin** [comment]
It looks like you still have an extra view controller (`ViewController`) in your app.
